Repository session-foundation/session-ios, pull requests merged in 2025-09, with the labels that each got.

#523 Fixed an issue where reactions weren't working in groups
  Session/Conversations/ConversationVC+Interaction.swift
  SessionMessagingKit/Messages/Message+Origin.swift
  SessionMessagingKit/Open Groups/Models/SOGSMessage.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
  SessionMessagingKit/Sending & Receiving/MessageSender.swift
Labels: bug, qa-tested, Jira

#531 Fix some highlighted search bubble covered by keyboard
  Session/Conversations/ConversationVC.swift
Labels: bug, qa-tested, Jira

#537 Removed a database call from onboarding
  Session/Onboarding/Onboarding.swift
  SessionMessagingKitTests/_TestUtilities/MockLibSessionCache.swift
  SessionTests/Onboarding/OnboardingSpec.swift
Labels: bug, Jira

#533 Centralised message deletion logic
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Media Viewing & Editing/MediaPageViewController.swift
  Session/Media Viewing & Editing/MediaTileViewController.swift
  Session/Meta/AppDelegate.swift
  SessionMessagingKit/Database/Models/ClosedGroup.swift
  SessionMessagingKit/Database/Models/DisappearingMessageConfiguration.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/Database/Models/SessionThread.swift
  SessionMessagingKit/Jobs/DisappearingMessagesJob.swift
  SessionMessagingKit/Jobs/GarbageCollectionJob.swift
  SessionMessagingKit/Jobs/GetExpirationJob.swift
  SessionMessagingKit/Open Groups/OpenGroupManager.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+Groups.swift
  SessionMessagingKit/Shared Models/MessageViewModel+DeletionActions.swift
  SessionMessagingKitTests/Open Groups/OpenGroupManagerSpec.swift
  SessionUtilitiesKit/LibSession/Types/ObservingDatabase.swift
Labels: bug, qa-tested, Jira

#540 Point release bug fixes
  .drone.jsonnet
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/Settings/ThreadDisappearingMessagesSettingsViewModel.swift
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionMessagingKit/Jobs/CheckForAppUpdatesJob.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+GroupInfo.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+UnsendRequests.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageSender+Groups.swift
  SessionMessagingKit/Sending & Receiving/MessageSender+Convenience.swift
  SessionUtilitiesKit/Database/Models/KeyValueStore.swift
  SessionUtilitiesKit/Dependency Injection/Dependencies.swift
  SessionUtilitiesKit/LibSession/Types/ObservingDatabase.swift
  SessionUtilitiesKit/Types/CancellationAwareAsyncStream.swift
  SessionUtilitiesKit/Types/CurrentValueAsyncStream.swift
  SessionUtilitiesKit/Types/StreamLifecycleManager.swift
  _SharedTestUtilities/TestDependencies.swift
Labels: bug

#534 Fix issue on some device long delete message is not wrapping
  Session/Conversations/Message Cells/Content Views/DeletedMessageView.swift
Labels: bug, qa-tested, Jira, dev-tested

#535 Fix input field not hiding when showing link preview modal
  Session/Conversations/ConversationVC+Interaction.swift
Labels: bug, qa-tested, Jira, dev-tested

#541 Added skip authentication flags for some group api calls
  SessionMessagingKit/Jobs/DisplayPictureDownloadJob.swift
  SessionMessagingKit/Jobs/RetrieveDefaultOpenGroupRoomsJob.swift
  SessionMessagingKit/Open Groups/OpenGroupAPI.swift
  SessionMessagingKitTests/Jobs/RetrieveDefaultOpenGroupRoomsJobSpec.swift
  SessionMessagingKitTests/Open Groups/OpenGroupAPISpec.swift
Labels: enhancement, qa-tested, Jira, dev-tested

#544 Update message request delete action
  Session/Utilities/UIContextualAction+Utilities.swift
Labels: enhancement, qa-tested, Jira

#546 Fix overly large file placeholder preview
  SignalUtilitiesKit/Media Viewing & Editing/MediaMessageView.swift
Labels: bug, qa-tested, Jira, dev-tested

#551 Align dark mode toggle setting design with other platforms
  Session/Settings/AppearanceViewModel.swift
Labels: enhancement, qa-tested, Jira, dev-tested

#555 Fix/layout issue and cleanup
  Session.xcodeproj/project.pbxproj
  Session/Closed Groups/EditGroupViewModel.swift
  Session/Settings/PrivacySettingsViewModel.swift
  Session/Settings/SettingsViewModel.swift
  Session/Shared/SessionTableViewController.swift
  Session/Shared/Types/EditableState.swift
  Session/Shared/Types/SessionCell+Styling.swift
  Session/Shared/Views/SessionCell+AccessoryView.swift
  Session/Shared/Views/SessionCell.swift
  Session/Shared/Views/SessionHeaderView.swift
  Session/Shared/Views/SessionHighlightingBackgroundLabel.swift
  SessionUIKit/Components/Separator.swift
  SessionUIKit/Utilities/UIView+Constraints.swift
Labels: bug, qa-tested, Jira

#556 Fix edit image features not working properly
  SessionUIKit/Style Guide/Values.swift
  SignalUtilitiesKit/Media Viewing & Editing/Image Editing/ImageEditorBrushViewController.swift
  SignalUtilitiesKit/Media Viewing & Editing/Image Editing/ImageEditorCanvasView.swift
  SignalUtilitiesKit/Media Viewing & Editing/Image Editing/ImageEditorPaletteView.swift
  SignalUtilitiesKit/Media Viewing & Editing/Image Editing/ImageEditorTextViewController.swift
Labels: bug, qa-tested, Jira, dev-tested

#560 Fix previously selected app icon not re-selected on toggle default off
  Session/Settings/AppIconViewModel.swift
  SessionUtilitiesKit/Types/UserDefaultsType.swift
Labels: bug, qa-tested, Jira, dev-tested

#564 Fixed a recovery password string which didn't have styling applied
  Session/Settings/RecoveryPasswordScreen.swift
Labels: bug, qa-tested, Jira, dev-tested

#552 Aligned deleted message bubble's font and text color
  Session/Conversations/Message Cells/CallMessageCell.swift
  Session/Conversations/Message Cells/Content Views/DeletedMessageView.swift
  SessionUIKit/Style Guide/ThemeManager.swift
  SessionUIKit/Style Guide/Values.swift
Labels: enhancement, qa-tested, Jira, dev-tested

#563 Fixed a home screen refresh issue
  Session.xcodeproj/project.pbxproj
  Session/Home/App Review/AppReviewPromptModel.swift
  Session/Home/HomeViewModel.swift
  SessionMessagingKit/Sending & Receiving/Notifications/PushNotificationAPI+SessionMessagingKit.swift
  SessionMessagingKit/Utilities/Threading+SessionMessagingKit.swift
  SessionMessagingKitTests/_TestUtilities/CustomArgSummaryDescribable+SessionMessagingKit.swift
  SessionNetworkingKit/LibSession/LibSession+Networking.swift
  SessionNetworkingKit/SOGS/SOGSAPI.swift
  SessionNetworkingKit/Utilities/ObservableKey+SessionNetworkingKit.swift
  SessionNetworkingKitTests/SOGS/SOGSAPISpec.swift
  SessionUtilitiesKit/Database/Storage.swift
  SessionUtilitiesKit/General/Logging.swift
  SessionUtilitiesKit/Observations/ObservableKey+SessionUtilitiesKit.swift
  SessionUtilitiesKit/Observations/ObservationManager.swift
Labels: bug, qa-tested, Jira

#569 Fixed an issue where UnsendRequests could be processed after their messages
  Session.xcodeproj/project.pbxproj
  Session/Settings/Views/NewTagView.swift
  Session/Shared/Views/SessionCell+AccessoryView.swift
  Session/Utilities/UIContextualAction+Utilities.swift
  SessionMessagingKit/Sending & Receiving/Errors/MessageReceiverError.swift
  SessionMessagingKit/Sending & Receiving/Pollers/SwarmPoller.swift
  SessionMessagingKit/Utilities/ExtensionHelper.swift
Labels: bug, qa-tested, Jira

#585 Flagged a bunch of functions as @MainActor to try to resolve crash
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/Input View/InputView.swift
  Session/Conversations/Input View/MentionSelectionView.swift
  Session/Home/HomeVC.swift
  Session/Media Viewing & Editing/GIFs/GifPickerViewController.swift
  Session/Meta/SessionApp.swift
  Session/Notifications/NotificationActionHandler.swift
  Session/Shared/Views/SessionCell.swift
  SessionUIKit/Components/ExpandableLabel.swift
  SessionUIKit/Components/Input View/InputTextView.swift
  SessionUIKit/Components/Input View/InputViewButton.swift
  SessionUIKit/Style Guide/ThemeManager.swift
  SignalUtilitiesKit/Media Viewing & Editing/Attachment Approval/AttachmentApprovalViewController.swift
  SignalUtilitiesKit/Media Viewing & Editing/Attachment Approval/AttachmentPrepViewController.swift
  SignalUtilitiesKit/Media Viewing & Editing/Attachment Approval/AttachmentTextToolbar.swift
Labels: bug, Jira

#582 Fixed a crash when unsubscribing from group PNs
  Session.xcodeproj/project.pbxproj
  SessionNetworkingKit/PushNotification/Models/SubscribeRequest.swift
  SessionNetworkingKit/PushNotification/Models/SubscribeResponse.swift
  SessionNetworkingKit/PushNotification/Models/UnsubscribeRequest.swift
  SessionNetworkingKit/PushNotification/Models/UnsubscribeResponse.swift
  SessionNetworkingKit/PushNotification/PushNotificationAPI.swift
Labels: bug, qa-tested, Jira
