Repository session-foundation/session-ios, pull requests merged in 2025-03, with the labels that each got.

#387 Fix broken CI
  .drone.jsonnet
Labels: bug

#369 Fix mentioning highlight background
  Session/Utilities/MentionUtilities.swift
  SessionUIKit/Components/HighlightMentionBackgroundView.swift
Labels: bug, qa-tested, Jira, dev-tested

#372 Make ONS with emoji work by punycode
  Session.xcodeproj/project.pbxproj
  Session.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Session/Meta/Settings.bundle/ThirdPartyLicenses.plist
  SessionSnodeKit/Networking/SnodeAPI.swift
  SessionSnodeKit/SnodeAPI/SnodeAPI.swift
Labels: enhancement, qa-tested, Jira, dev-tested

#378 Sort group member change control messages deterministically
  SessionMessagingKit/Database/Models/ClosedGroup.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+Groups.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageSender+Groups.swift
  SessionMessagingKitTests/Sending & Receiving/MessageSenderGroupsSpec.swift
Labels: bug, qa-tested, Jira

#380 Fixed an issue where the read receipt wouldn't show while the conversation was open
  SessionMessagingKit/Database/Models/Interaction.swift
  SessionUtilitiesKit/Database/Types/PagedDatabaseObserver.swift
Labels: bug, qa-tested, Jira

#381 Fixed a bug where changing the display name wouldn't result in a default display pic update
  SessionUIKit/Components/PlaceholderIcon.swift
Labels: bug, qa-tested, Jira

#388 Fixed a crash when opening message info in a community
  Session/Conversations/Context Menu/ContextMenuVC+Action.swift
Labels: bug, qa-tested, Jira

#391 Dependency access crash fix
  SessionUtilitiesKit/Dependency Injection/Dependencies.swift
Labels: bug, Jira

#393 Fixed an issue where groups with only some config dumps wouldn't load
  Session/Onboarding/Onboarding.swift
  SessionMessagingKit/LibSession/LibSession+SessionMessagingKit.swift
  SessionMessagingKitTests/_TestUtilities/MockLibSessionCache.swift
Labels: bug, Jira

#392 Fix GRDB Assertion
  Session.xcodeproj/project.pbxproj
  Session.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Session/Conversations/ConversationSearch.swift
  Session/Conversations/ConversationVC.swift
  Session/Home/GlobalSearch/GlobalSearchViewController.swift
  Session/Home/HomeVC.swift
  Session/Media Viewing & Editing/DocumentTitleViewController.swift
  Session/Media Viewing & Editing/MediaTileViewController.swift
  Session/Shared/Types/PagedObservationSource.swift
  SessionMessagingKit/Jobs/ConfigMessageReceiveJob.swift
  SessionMessagingKit/Jobs/MessageReceiveJob.swift
  SessionMessagingKit/Open Groups/OpenGroupAPI.swift
  SessionMessagingKitTests/Open Groups/OpenGroupAPISpec.swift
  SessionSnodeKit/Types/PreparedRequest.swift
  SessionUtilitiesKit/Database/Storage.swift
  SessionUtilitiesKit/Database/StorageError.swift
  SessionUtilitiesKit/Database/Utilities/Database+Utilities.swift
  SessionUtilitiesKit/General/Logging.swift
Labels: bug, Jira

#379 Network status not updating in certain conditions
  Session/Path/PathStatusView.swift
Labels: bug, qa-tested, Jira

#376 Add accessibility id and label to cells in share to Session screen
  SessionShareExtension/SimplifiedConversationCell.swift
Labels: bug, Jira

#397 Fix a config push crash
  SessionMessagingKit/LibSession/LibSession+SessionMessagingKit.swift
  SessionMessagingKit/LibSession/Types/Config.swift
Labels: bug, Jira

#396 Attempt to prevent an odd NaN crash
  Session.xcodeproj/project.pbxproj
  Session/Meta/AppDelegate.swift
Labels: bug, Jira
