Repository session-foundation/session-ios, pull requests merged in 2025-08, with the labels that each got.

#481 Fix modal input clear button
  Session/Shared/SessionTableViewController.swift
  SessionUIKit/Components/ConfirmationModal.swift
Labels: bug, qa-tested, Jira

#492 Fixed an issue with video attachment quality
  Session/Media Viewing & Editing/PhotoLibrary.swift
Labels: bug, qa-tested, Jira

#515 Fixed an issue where we were storing the 'softfork' version in the 'hardfork' value
  SessionSnodeKit/SnodeAPI/SnodeAPI.swift
Labels: bug

#484 Fix emoji reacts notification
  .drone.jsonnet
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+VisibleMessages.swift
  SessionMessagingKit/Sending & Receiving/Notifications/NotificationsManagerType.swift
Labels: bug, qa-tested, Jira

#504 Fix join community tabbar spacing
  Session/Open Groups/JoinOpenGroupVC.swift
Labels: bug, qa-tested, Jira, dev-tested

#507 Fix incorrect duration for uploading voice message
  Session/Conversations/Message Cells/Content Views/VoiceMessageView.swift
Labels: bug, qa-tested, Jira, dev-tested

#513 Fix hash id displayed instead of contact name in apple watch call
  Session/Calls/Call Management/SessionCallManager+CXCallController.swift
  Session/Calls/Call Management/SessionCallManager.swift
Labels: bug, qa-tested, Jira, dev-tested

#514 Fixed an issue where Desktop can't download iOS attachments
  SessionMessagingKit/Database/Models/Attachment.swift
Labels: bug, qa-tested, Jira

#511 Fix reply does not cancel search state on conversation
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/ConversationVC.swift
Labels: bug, qa-tested, Jira, dev-tested

#509 Stopped some message types making conversations become visible
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
Labels: bug, qa-tested, Jira

#510 Fixed an issue where the unread count could incorrectly get reset
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
Labels: bug, qa-tested, Jira

#512 Fixed an issue where notification settings weren't being respected for PNs
  Session.xcodeproj/project.pbxproj
  Session/Meta/AppDelegate.swift
  Session/Notifications/NotificationPresenter.swift
  SessionMessagingKit/Calls/NoopSessionCallManager.swift
  SessionMessagingKit/LibSession/LibSession+SessionMessagingKit.swift
  SessionMessagingKit/Sending & Receiving/Notifications/NotificationsManagerType.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionSnodeKit/LibSession/LibSession+Networking.swift
  SessionUtilitiesKit/Dependency Injection/Dependencies.swift
  SessionUtilitiesKit/Dependency Injection/NoopDependency.swift
  SessionUtilitiesKit/General/AppContext.swift
  _SharedTestUtilities/TestDependencies.swift
Labels: bug, qa-tested, Jira

#518 Fix incorrectly selecting image when scrolling thru collection
  Session/Media Viewing & Editing/ImagePickerController.swift
Labels: bug, qa-tested, Jira

#519 Fix accessory labels expansion causing squashed content
  Session/Shared/Views/SessionCell+AccessoryView.swift
  Session/Shared/Views/SessionCell.swift
  Session/Shared/Views/SessionHighlightingBackgroundLabel.swift
Labels: bug, qa-tested, Jira, dev-tested

#529 Fixed an issue with the home screen empty state and MR banner
  Session/Home/HomeViewModel.swift
Labels: bug, qa-tested, Jira

#530 String updates and new confirmation dialogs
  Session/Conversations/ConversationVC+Interaction.swift
  SessionMessagingKit/Database/Models/Attachment.swift
  SessionUtilitiesKit/General/String+Utilities.swift
Labels: enhancement, qa-tested, Jira

#520 Fix unresponsive textfield due to small hit area
  SessionUIKit/Components/SwiftUI/SessionTextField.swift
Labels: bug, qa-tested, Jira, dev-tested

#521 Updated expiresStartedAtMs when message has been sent successfully
  Session/Conversations/Context Menu/ContextMenuVC+ActionView.swift
  Session/Conversations/ConversationViewModel.swift
  SessionMessagingKit/Sending & Receiving/MessageSender+Convenience.swift
Labels: bug, qa-tested, Jira
