Repository session-foundation/session-ios, pull requests merged in 2025-06, with the labels that each got.

#451 DBR - 5 - Config message handling
  Session/Conversations/ConversationViewModel.swift
  Session/Home/HomeViewModel.swift
  Session/Media Viewing & Editing/MessageInfoScreen.swift
  Session/Onboarding/Onboarding.swift
  Session/Settings/DeveloperSettingsViewModel.swift
  SessionMessagingKit/Database/Migrations/_014_GenerateInitialUserConfigDumps.swift
  SessionMessagingKit/Database/Migrations/_015_BlockCommunityMessageRequests.swift
  SessionMessagingKit/Database/Models/Profile.swift
  SessionMessagingKit/Jobs/GroupInviteMemberJob.swift
  SessionMessagingKit/Jobs/GroupLeavingJob.swift
  SessionMessagingKit/Jobs/UpdateProfilePictureJob.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+Contacts.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+ConvoInfoVolatile.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+Shared.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+SharedGroup.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+UserGroups.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+UserProfile.swift
  SessionMessagingKit/LibSession/LibSession+SessionMessagingKit.swift
  SessionMessagingKit/Messages/LibSessionMessage.swift
  SessionMessagingKit/Messages/Visible Messages/VisibleMessage+Profile.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+Groups.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+LibSession.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
  SessionMessagingKit/Sending & Receiving/MessageSender.swift
  SessionMessagingKit/Sending & Receiving/Notifications/Models/NotificationMetadata.swift
  SessionMessagingKit/Sending & Receiving/Notifications/NotificationsManagerType.swift
  SessionMessagingKit/Sending & Receiving/Notifications/PushNotificationAPI.swift
  SessionMessagingKit/Utilities/ExtensionHelper.swift
  SessionMessagingKitTests/Sending & Receiving/MessageReceiverGroupsSpec.swift
  SessionMessagingKitTests/Utilities/ExtensionHelperSpec.swift
  SessionMessagingKitTests/_TestUtilities/CommonSMKMockExtensions.swift
  SessionMessagingKitTests/_TestUtilities/MockExtensionHelper.swift
  SessionMessagingKitTests/_TestUtilities/MockLibSessionCache.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionSnodeKit/Types/BencodeResponse.swift
Labels: enhancement, Jira

#467 Fixed the SwiftUI accessibility extension
  SessionUIKit/Components/SwiftUI/SessionTextField.swift
  SessionUIKit/Utilities/SwiftUI+Utilities.swift
Labels: bug, Jira

#468 Fix last updated timestamp position
  SessionUIKit/Screens/Settings/SessionNetworkScreen/SessionNetworkScreen.swift
Labels: bug

#471 Fix local notification
  Session/Notifications/NotificationPresenter.swift
Labels: bug, Jira

#475 Made a number of tweaks to try to improve some memory usage
  .swiftlint.yml
  Session.xcodeproj/project.pbxproj
  Session/Calls/Call Management/SessionCall.swift
  Session/Calls/WebRTC/WebRTCSession.swift
  Session/Closed Groups/NewClosedGroupVC.swift
  Session/Conversations/ConversationVC.swift
  Session/Conversations/ConversationViewModel.swift
  Session/Conversations/Message Cells/CallMessageCell.swift
  Session/Conversations/Message Cells/Content Views/DisappearingMessageTimerView.swift
  Session/Home/HomeVC.swift
  Session/Home/Message Requests/Views/MessageRequestsCell.swift
  Session/Media Viewing & Editing/DocumentTitleViewController.swift
  Session/Media Viewing & Editing/MediaPageViewController.swift
  Session/Media Viewing & Editing/MediaTileViewController.swift
  Session/Meta/AppDelegate.swift
  Session/Meta/MainAppContext.swift
  Session/Shared/SessionTableViewController.swift
  Session/Utilities/MockDataGenerator.swift
  SessionShareExtension/ThreadPickerVC.swift
  SessionUIKit/Components/SwiftUI/AdaptiveText.swift
  SessionUIKit/Screens/Settings/SessionNetworkScreen/SessionNetworkScreen.swift
  SessionUIKit/Style Guide/Themes/ThemedAttributedString.swift
  SessionUtilitiesKit/Combine/ReplaySubject.swift
  SessionUtilitiesKit/Database/Types/PagedDatabaseObserver.swift
  SessionUtilitiesKit/Utilities/NSAttributedString+Utilities.swift
Labels: bug, Jira
