Repository session-foundation/session-ios, pull requests merged in 2025-04, with the labels that each got.

#370 Add feedbacks for actions in message info screen
  Session/Conversations/Context Menu/ContextMenuVC+Action.swift
  Session/Conversations/Context Menu/ContextMenuVC+ActionView.swift
  Session/Conversations/Context Menu/ContextMenuVC+EmojiReactsView.swift
  Session/Conversations/Context Menu/ContextMenuVC.swift
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/Input View/InputView.swift
  Session/Media Viewing & Editing/MessageInfoScreen.swift
  SessionUIKit/Components/SwiftUI/Toast.swift
Labels: enhancement, qa-tested, Jira, dev-tested

#386 Added block and delete functionality to contact list
  Session/Conversations/Settings/ThreadSettingsViewModel.swift
  Session/Home/GlobalSearch/GlobalSearchViewController.swift
  Session/Shared/FullConversationCell.swift
  Session/Utilities/UIContextualAction+Utilities.swift
  SessionMessagingKit/Database/Models/SessionThread.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+MessageRequests.swift
  SessionMessagingKit/Shared Models/SessionThreadViewModel.swift
Labels: enhancement, qa-tested, Jira

#398 Defaulted the initial "invited" control message to be read for the admin
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageSender+Groups.swift
Labels: bug, qa-tested, Jira

#402 Updated dev settings to only reset settings which have been set
  Session/Settings/DeveloperSettingsViewModel.swift
  SessionUtilitiesKit/Dependency Injection/Dependencies.swift
  SessionUtilitiesKit/General/Feature.swift
Labels: bug, qa-tested, Jira

#408 Fixed an index out of bounds crash when ending a message with a mention
  Session/Utilities/MentionUtilities.swift
Labels: bug, qa-tested, Jira

#406 Removed YYImage and libWebP, fixed a couple of bugs
  BUILDING.md
  Session.xcodeproj/project.pbxproj
  Session.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Session/Calls/Call Management/SessionCall.swift
  Session/Calls/CallVC.swift
  Session/Closed Groups/EditGroupViewModel.swift
  Session/Conversations/Message Cells/Content Views/MediaView.swift
  Session/Conversations/Settings/ProfilePictureVC.swift
  Session/Conversations/Settings/ThreadSettingsViewModel.swift
  Session/Media Viewing & Editing/GIFs/GifPickerCell.swift
  Session/Media Viewing & Editing/MediaDetailViewController.swift
  Session/Meta/Settings.bundle/ThirdPartyLicenses.plist
  Session/Shared/UserListViewModel.swift
  SessionMessagingKit/Database/Models/Attachment.swift
  SessionUIKit/Components/AnimatedImageView.swift
  SessionUIKit/Components/ProfilePictureView.swift
  SessionUtilitiesKit/Media/Data+Image.swift
  SessionUtilitiesKit/Media/UTType+Utilities.swift
  SignalUtilitiesKit/Media Viewing & Editing/MediaMessageView.swift
Labels: enhancement, qa-tested, Jira

#407 Updated a few accessibility ids for automated tests
  Session/Conversations/ConversationVC.swift
  Session/Conversations/Settings/ThreadSettingsViewModel.swift
  Session/Settings/SettingsViewModel.swift
  SessionTests/Conversations/Settings/ThreadSettingsViewModelSpec.swift
Labels: qa-tested, Jira

#363 Improvements on Calls
  Scripts/LintLocalizableStrings.swift
  Session.xcodeproj/project.pbxproj
  Session/Calls/Call Management/SessionCall.swift
  Session/Calls/Call Management/SessionCallManager+Action.swift
  Session/Calls/Call Management/SessionCallManager+CXProvider.swift
  Session/Calls/Call Management/SessionCallManager.swift
  Session/Calls/CallVC.swift
  Session/Calls/Views & Modals/CallMissedTipsModal.swift
  Session/Calls/Views & Modals/IncomingCallBanner.swift
  Session/Calls/Views & Modals/MiniCallView.swift
  Session/Calls/WebRTC/WebRTCSession+MessageHandling.swift
  Session/Calls/WebRTC/WebRTCSession.swift
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/ConversationVC.swift
  Session/Conversations/Views & Modals/ConversationTitleView.swift
  Session/Media Viewing & Editing/SendMediaNavigationController.swift
  Session/Meta/AppDelegate.swift
  Session/Meta/Session-Info.plist
  Session/Meta/Translations/InfoPlist.xcstrings
  Session/Notifications/PushRegistrationManager.swift
  Session/Open Groups/JoinOpenGroupVC.swift
  Session/Settings/PrivacySettingsViewModel.swift
  Session/Shared/ScanQRCodeScreen.swift
  Session/Shared/SessionTableViewController.swift
  Session/Shared/SessionTableViewModel.swift
  Session/Utilities/Permissions.swift
  SessionMessagingKit/Calls/CallManagerProtocol.swift
  SessionMessagingKit/Calls/CallMode.swift
  SessionMessagingKit/Calls/CurrentCallProtocol.swift
  SessionMessagingKit/Calls/EndCallMode.swift
  SessionMessagingKit/Calls/NoopSessionCallManager.swift
  SessionMessagingKit/Sending & Receiving/Message Handling/MessageReceiver+Calls.swift
  SessionMessagingKit/Utilities/Preferences.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionUIKit/Components/ConfirmationModal.swift
  SessionUtilitiesKit/General/Constants.swift
  SessionUtilitiesKit/Types/UserDefaultsType.swift
  SessionUtilitiesKit/Utilities/Permissions.swift
Labels: bug, qa-tested, Jira

#411 Added support for rendering quotes with attachments and bug fixes
  Session/Conversations/ConversationViewModel.swift
  Session/Conversations/Message Cells/VisibleMessageCell.swift
  Session/Media Viewing & Editing/MessageInfoScreen.swift
  SessionMessagingKit/Shared Models/MessageViewModel.swift
Labels: bug, qa-tested, Jira

#413 Fixed a potential deadlock which could occur when typing
  Session/Conversations/Input View/InputView.swift
Labels: bug

#403 Updated to the latest libQuic
  Session.xcodeproj/project.pbxproj
  Session.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Session/Meta/AppDelegate.swift
  SessionMessagingKit/Messages/Message.swift
  SessionMessagingKit/Sending & Receiving/Errors/MessageReceiverError.swift
  SessionMessagingKit/Sending & Receiving/MessageReceiver.swift
  SessionNotificationServiceExtension/NSENotificationPresenter.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionSnodeKit/Types/BatchResponse.swift
  SessionUtilitiesKit/Database/Storage.swift
Labels: enhancement, Jira

#418 Memory management cleanup, tweak MRR logic, libSession 1.3.1
  Session.xcodeproj/project.pbxproj
  Session.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  Session.xcodeproj/xcshareddata/xcschemes/Session.xcscheme
  Session.xcodeproj/xcshareddata/xcschemes/Session_CompileLibSession.xcscheme
  Session/Conversations/ConversationVC+Interaction.swift
  SessionMessagingKit/Crypto/Crypto+SessionMessagingKit.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+GroupKeys.swift
  SessionMessagingKit/LibSession/Types/Config.swift
  SessionMessagingKitTests/LibSession/LibSessionUtilSpec.swift
  SessionSnodeKit/LibSession/LibSession+Networking.swift
  SessionSnodeKitTests/Types/BatchRequestSpec.swift
  SessionUtilitiesKit/General/Collection+Utilities.swift
  SessionUtilitiesKit/LibSession/Utilities/TypeConversion+Utilities.swift
  SessionUtilitiesKitTests/LibSession/Utilities/TypeConversionUtilitiesSpec.swift
Labels: bug

#421 Further memory management fixes
  SessionMessagingKit/Crypto/Crypto+LibSession.swift
  SessionMessagingKit/Crypto/Crypto+SessionMessagingKit.swift
  SessionMessagingKit/LibSession/Config Handling/LibSession+GroupKeys.swift
  SessionMessagingKit/LibSession/Types/Config.swift
  SessionMessagingKit/Open Groups/Crypto/Crypto+OpenGroupAPI.swift
  SessionMessagingKitTests/LibSession/LibSessionUtilSpec.swift
  SessionSnodeKit/LibSession/LibSession+Networking.swift
  SessionUtilitiesKit/Crypto/Crypto+SessionUtilitiesKit.swift
Labels: bug

#424 Remove recursion from C conversion to prevent stack overflows
  SessionUtilitiesKit/General/Collection+Utilities.swift
Labels: bug

#431 Fixed a rare crash when cancelling a database query upstream
  SessionUtilitiesKit/Database/Storage.swift
Labels: bug

#435 Reworked memory conversion to explicitly allocate and free
  Session.xcodeproj/project.pbxproj
  SessionUtilitiesKit/General/Collection+Utilities.swift
Labels: bug

#429 Replaced usages of NSCache with LRUCache (future proofing)
  Session.xcodeproj/project.pbxproj
  Session/Conversations/ConversationVC+Interaction.swift
  Session/Conversations/ConversationVC.swift
  Session/Conversations/Message Cells/CallMessageCell.swift
  Session/Conversations/Message Cells/Content Views/MediaAlbumView.swift
  Session/Conversations/Message Cells/Content Views/MediaView.swift
  Session/Conversations/Message Cells/DateHeaderCell.swift
  Session/Conversations/Message Cells/InfoMessageCell.swift
  Session/Conversations/Message Cells/MessageCell.swift
  Session/Conversations/Message Cells/TypingIndicatorCell.swift
  Session/Conversations/Message Cells/UnreadMarkerCell.swift
  Session/Conversations/Message Cells/VisibleMessageCell.swift
  Session/Media Viewing & Editing/MessageInfoScreen.swift
  Session/Meta/Session+SNUIKit.swift
  Session/Settings/Views/ThemeMessagePreviewView.swift
  Session/Shared/ScreenLockWindow.swift
  Session/Shared/SessionCarouselView+SwiftUI.swift
  SessionMessagingKit/Database/Models/LinkPreview.swift
  SessionNotificationServiceExtension/NSEConstants.swift
  SessionNotificationServiceExtension/NSENotificationPresenter.swift
  SessionNotificationServiceExtension/NotificationServiceExtension.swift
  SessionShareExtension/SAEScreenLockViewController.swift
  SessionShareExtension/ShareNavController.swift
  SessionUIKit/Types/Localization.swift
  SessionUIKit/Utilities/Date+Utilities.swift
  SessionUIKit/Utilities/ScreenLock+Errors.swift
  SessionUtilitiesKit/General/General.swift
  SessionUtilitiesKit/General/LRUCache.swift
  SessionUtilitiesKit/General/NSCache+Utilities.swift
  SessionUtilitiesKit/General/ScreenLock.swift
  _SharedTestUtilities/MockGeneralCache.swift
Labels: enhancement
